---
  root: true

  parser: babel-eslint

  extends:
    - airbnb
    - plugin:prettier/recommended

  env:
    browser: true
    jest: true

  rules:
    # We prefer .js filename extension
    react/jsx-filename-extension: off

    # We're using modules from dev dependencies in config scripts
    import/no-extraneous-dependencies: off
