---
  root: true

  parser: babel-eslint

  extends:
    - airbnb

  env:
    browser: true

  rules:
    # We prefer .js filename extension
    react/jsx-filename-extension: off

    # We're using modules from dev dependencies in config scripts
    import/no-extraneous-dependencies: off
